CREATE DATABASE IF NOT EXISTS flowershop;

USE flowershop;

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL
);